#Analizar Datos
Ver comportamientos
1. Porque y que es
2. Estadistica Descriptiva
3. Graficas para analizar
4. Casos de Estudios que toca Solucionar
5. Proyecto: Mitad a mitad de corte (24 de febrero)  y el otro a final de corte (24 de marzo) / 1 Jugador de LOL / Analizar el como juega y su desempeño / Revisar el Meta y revizar las bases de datos / TRevisar quienes conforman todo league of legends / Ver la final de LOL porque los europeos jugaron muy raro gracias al analisis de datos / Primer analisis: Analisis Estadistica (promedio, media, mediana, etc.) Segundo analisis: Analisis EDA (Limpia los datos y los revisa), resumen ejecutivo y el otro explicar los datos y un informe libre, Analizar mucho mas de 10 datos (ajjajaja), revisar mucho en que mejorar, revizar los datos atipicos y el porque se generaron. NOOOOOO SUBESTIMAAAARRRRR
6. Nota (30%): Valoracion del cliente y la otra mitad la profe.


In [ ]:
print("tu nombre es"+ " "+input("como te llamas?"))
print("tu edad es " + input("cual es tu edad"))

nom= input("cual es tu nombre?")
edad= input("cual es tu edad")

print(f"tu nombre es {nom} y tu edad es {edad}")

como te llamas?f
tu nombre es f
cual es tu edad2
tu edad es 2
cual es tu nombre?andres
cual es tu edad13
tu nombre es andres y tu edad es 13


In [ ]:
nom= input("cual es tu nombre?")
edad= int(input("cual es tu edad"))

nom1= input("cual es tu nombre?")
edad1= int(input("cual es tu edad"))

media=(edad+edad1)/2
print(media)

cual es tu nombre?ju
cual es tu edad12
cual es tu nombre?an
cual es tu edad24
18.0


In [ ]:
#Filas=registros
#Columnas=features
#Dataframe=

In [1]:
import numpy as np
import pandas as pd

In [2]:
#Convertir de lista a dataframe
ventas=pd.Series([22,15,70])
ventas

0    22
1    15
2    70
dtype: int64

In [6]:
venta=pd.Series([22,15,70],index=["Enero","Febrero","Marzo"])
venta[0]

<ipython-input-6-22bfa69a1e4b>:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  venta[0]


22

In [8]:
venta["Enero"]

22

In [9]:
venta.dtype

dtype('int64')

In [10]:
#Para visualizacion de features
venta.index

Index(['Enero', 'Febrero', 'Marzo'], dtype='object')

In [11]:
#Para obtener los valores de las featues
venta.values

array([22, 15, 70])

In [12]:
venta.name="Ventas 2025"
venta

Enero      22
Febrero    15
Marzo      70
Name: Ventas 2025, dtype: int64

In [13]:
venta.index.name="meses"
venta

meses
Enero      22
Febrero    15
Marzo      70
Name: Ventas 2025, dtype: int64

In [14]:
venta.shape

(3,)

In [15]:
#diccionarios no tienen index
#clave unica y valor unico a la clave
#es mutable
diccionario={"Enero":22,"Febrero":15,"Marzo":70}
diccionario

{'Enero': 22, 'Febrero': 15, 'Marzo': 70}

In [16]:
type(diccionario)

dict

In [18]:
venta1=pd.Series(diccionario)
venta1

Enero      22
Febrero    15
Marzo      70
dtype: int64

In [19]:
alex=pd.Series(diccionario,index=["Enero","Febrero","Marzo","Abril"])
alex

Enero      22.0
Febrero    15.0
Marzo      70.0
Abril       NaN
dtype: float64

In [24]:
medidas=pd.DataFrame(
    {"Humedad":[41,20,30,80],
     "Salinidad":[22,15,30,80],
     "Sensorica":["si","no","no","no"],
     "Acidez":["Alta","Media","Baja","Baja"],
     "PH":[1,7,14,13]},
    index=["La Ureña","Paso Chico","La Laguna","Los Teres"])
medidas

Humedad  Salinidad Sensorica Acidez  PH
La Ureña         41         22        si   Alta   1
Paso Chico       20         15        no  Media   7
La Laguna        30         30        no   Baja  14
Los Teres        80         80        no   Baja  13

In [25]:
medidas.index.name="Veredas"
medidas

Humedad  Salinidad Sensorica Acidez  PH
Veredas                                            
La Ureña         41         22        si   Alta   1
Paso Chico       20         15        no  Media   7
La Laguna        30         30        no   Baja  14
Los Teres        80         80        no   Baja  13

In [26]:
medidas.Humedad

Veredas
La Ureña      41
Paso Chico    20
La Laguna     30
Los Teres     80
Name: Humedad, dtype: int64

In [46]:
medidas[["Acidez", "PH"]]

Acidez  PH
Veredas              
La Ureña     Alta   1
Paso Chico  Media   7
La Laguna    Baja  14
Los Teres    Baja  13

In [50]:
medidas.dtypes

Humedad       int64
Salinidad     int64
Sensorica    object
Acidez       object
PH            int64
dtype: object

In [51]:
medidas.axes

[Index(['La Ureña', 'Paso Chico', 'La Laguna', 'Los Teres'], dtype='object', name='Veredas'),
 Index(['Humedad', 'Salinidad', 'Sensorica', 'Acidez', 'PH'], dtype='object')]

In [53]:
medidas.values

array([[41, 22, 'si', 'Alta', 1],
       [20, 15, 'no', 'Media', 7],
       [30, 30, 'no', 'Baja', 14],
       [80, 80, 'no', 'Baja', 13]], dtype=object)

In [54]:
medidas.shape

(4, 5)

In [ ]:
elementos={"numero:"}

In [61]:
elementos=pd.DataFrame({"número atómico":[1,6,47,88],
                        "Masa atómica":[1,12,107,226],
                        "Familia":["No metal","No metal","Metal","Metal"]}, index=["Plata","Oro","Cobre","Platino"])
elementos

número atómico  Masa atómica   Familia
Plata                 1             1  No metal
Oro                   6            12  No metal
Cobre                47           107     Metal
Platino              88           226     Metal

In [62]:
elementos.index.name="Elementos"
elementos

número atómico  Masa atómica   Familia
Elementos                                        
Plata                   1             1  No metal
Oro                     6            12  No metal
Cobre                  47           107     Metal
Platino                88           226     Metal

In [64]:

medida_2020={"Ag":2,"Au":5,"Cu":3,"Pt":2}
medida_2021={"Ag":4,"Au":3,"Cu":6,"Pt":1}
medida_2022={"Ag":8,"Au":2,"Cu":15,"Pt":0}
medida_2023={"Ag":5,"Au":1,"Cu":0,"Pt":5}
medida_2024={"Ag":7,"Au":0,"Cu":3,"Pt":2}
medida_2025={"Ag":9,"Au":1,"Cu":3,"Pt":5}

In [71]:
medida=pd.DataFrame([medida_2020, medida_2021, medida_2022, medida_2023, medida_2024, medida_2025], index=["2020","2021","2022","2023","2024","2025"])
medida

Ag  Au  Cu  Pt
2020   2   5   3   2
2021   4   3   6   1
2022   8   2  15   0
2023   5   1   0   5
2024   7   0   3   2
2025   9   1   3   5

In [72]:
medida.index.name="Años"
medida

Ag  Au  Cu  Pt
Años                
2020   2   5   3   2
2021   4   3   6   1
2022   8   2  15   0
2023   5   1   0   5
2024   7   0   3   2
2025   9   1   3   5

In [73]:
medida.shape

(6, 4)

In [80]:
elementos.shape

(4, 3)

In [74]:
medida.index

Index(['2020', '2021', '2022', '2023', '2024', '2025'], dtype='object', name='Años')

In [81]:
elementos.index

Index(['Plata', 'Oro', 'Cobre', 'Platino'], dtype='object', name='Elementos')

In [75]:
medida.dtypes

Ag    int64
Au    int64
Cu    int64
Pt    int64
dtype: object

In [82]:
elementos.dtypes

número atómico     int64
Masa atómica       int64
Familia           object
dtype: object

In [78]:
medida.values

array([[ 2,  5,  3,  2],
       [ 4,  3,  6,  1],
       [ 8,  2, 15,  0],
       [ 5,  1,  0,  5],
       [ 7,  0,  3,  2],
       [ 9,  1,  3,  5]])

In [83]:
elementos.values

array([[1, 1, 'No metal'],
       [6, 12, 'No metal'],
       [47, 107, 'Metal'],
       [88, 226, 'Metal']], dtype=object)

In [77]:
medida.axes

[Index(['2020', '2021', '2022', '2023', '2024', '2025'], dtype='object', name='Años'),
 Index(['Ag', 'Au', 'Cu', 'Pt'], dtype='object')]

In [84]:
elementos.axes

[Index(['Plata', 'Oro', 'Cobre', 'Platino'], dtype='object', name='Elementos'),
 Index(['número atómico', 'Masa atómica', 'Familia'], dtype='object')]

In [79]:
medida[["Ag","Au"]]

Ag  Au
Años        
2020   2   5
2021   4   3
2022   8   2
2023   5   1
2024   7   0
2025   9   1

In [86]:
elementos[["número atómico","Masa atómica"]]

número atómico  Masa atómica
Elementos                              
Plata                   1             1
Oro                     6            12
Cobre                  47           107
Platino                88           226